controller:
  replicas: 1
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  
  serviceType: ClusterIP
  servicePort: 8080
  
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
  
  jenkinsUrl: "http://jenkins:8080"
  
  ingress:
    enabled: false

persistence:
  enabled: true
  size: 8Gi
  storageClass: "gp2"

agent:
  enabled: true
  defaultsProviderTemplate: "default"
  podRetention: "Never"
  containerCap: 10
