controller:
  image:
    repository: "jenkins/jenkins"
    tag: "2.479.1-lts-jdk17"
  replicas: 1
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  
  serviceType: ClusterIP
  servicePort: 8080
  
  installPlugins:
    - kubernetes:4203.v1dd44f5b_1cf9
    - workflow-aggregator:600.vb_57cdd26fdd7
    - git:5.2.2
    - configuration-as-code:1856.vccdd26226312
  
  jenkinsUrl: "http://jenkins:8080"
  
  ingress:
    enabled: false

persistence:
  enabled: true
  size: 8Gi
  storageClass: "gp2"

agent:
  enabled: true
  defaultsProviderTemplate: "default"
  podRetention: "Never"
  containerCap: 10
