replicaCount: 2

image:
  repository: 053414411835.dkr.ecr.us-east-1.amazonaws.com/django-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: django.example.com
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

env:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DATABASE_HOST: "your-rds-endpoint"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "djangodb"
  DATABASE_USER: "admin"

secrets:
  DATABASE_PASSWORD: "your-password"

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: true
  name: ""

imagePullSecrets: []
# imagePullSecrets:
#   - name: ecr-registry-secret
