apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-app.fullname" . }}-config
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
data:
  DEBUG: {{ .Values.env.DEBUG | quote }}
  ALLOWED_HOSTS: {{ .Values.env.ALLOWED_HOSTS | quote }}
  DATABASE_HOST: {{ .Values.env.DATABASE_HOST | quote }}
  DATABASE_PORT: {{ .Values.env.DATABASE_PORT | quote }}
  DATABASE_NAME: {{ .Values.env.DATABASE_NAME | quote }}
  DATABASE_USER: {{ .Values.env.DATABASE_USER | quote }}
