apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-app.fullname" . }}-secret
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.secrets.DATABASE_PASSWORD | b64enc | quote }}
